// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleWKT

/// AppConnectorInstanceConfig defines the instance config of a AppConnector.
public struct AppConnectorInstanceConfig: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Required. A monotonically increasing number generated and maintained
  /// by the API provider. Every time a config changes in the backend, the
  /// sequenceNumber should be bumped up to reflect the change.
  public var sequenceNumber: Swift.Int64 = Swift.Int64()

  /// The SLM instance agent configuration.
  public var instanceConfig: GoogleWKT.`Any`? = nil

  /// NotificationConfig defines the notification mechanism that the remote
  /// instance should subscribe to in order to receive notification.
  public var notificationConfig: NotificationConfig? = nil

  /// ImageConfig defines the GCR images to run for the remote agent's control
  /// plane.
  public var imageConfig: ImageConfig? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `AppConnectorInstanceConfig`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = AppConnectorInstanceConfig().with { $0.sequenceNumber = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let sequenceNumber = CodingKeys(stringValue: "sequenceNumber")
    static let instanceConfig = CodingKeys(stringValue: "instanceConfig")
    static let notificationConfig = CodingKeys(stringValue: "notificationConfig")
    static let imageConfig = CodingKeys(stringValue: "imageConfig")

    static let _knownKeys: Set<Swift.String> = [
      "sequenceNumber",
      "instanceConfig",
      "notificationConfig",
      "imageConfig",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.Int64.self, forKey: .sequenceNumber) {
      self.sequenceNumber = value
    }
    self.instanceConfig = try container.decodeIfPresent(
      GoogleWKT.`Any`.self, forKey: .instanceConfig)
    self.notificationConfig = try container.decodeIfPresent(
      NotificationConfig.self, forKey: .notificationConfig)
    self.imageConfig = try container.decodeIfPresent(ImageConfig.self, forKey: .imageConfig)
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.sequenceNumber, forKey: .sequenceNumber)
    try container.encodeIfPresent(self.instanceConfig, forKey: .instanceConfig)
    try container.encodeIfPresent(self.notificationConfig, forKey: .notificationConfig)
    try container.encodeIfPresent(self.imageConfig, forKey: .imageConfig)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.beyondcorp.appconnectors.v1.AppConnectorInstanceConfig"
  }
  public init(fromAny any: GoogleWKT.`Any`) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.Struct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
