// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
#if canImport(FoundationNetworking)
  import FoundationNetworking
#endif
@_spi(GoogleCloudInternal) public import GoogleCloudLocation
@_spi(GoogleCloudInternal) public import GoogleIAMV1
@_spi(GoogleCloudInternal) public import GoogleLongRunning
@_spi(GoogleCloudInternal) public import GoogleWKT
@_spi(GoogleCloudInternal) public import GoogleGax

/// API Overview:
///
/// The `beyondcorp.googleapis.com` service implements the Google Cloud
/// BeyondCorp API.
///
/// Data Model:
///
/// The AppConnectorsService exposes the following resource:
///
/// * AppConnectors, named as follows:
///   `projects/{project_id}/locations/{location_id}/appConnectors/{app_connector_id}`.
///
/// The AppConnectorsService provides methods to manage
/// (create/read/update/delete) BeyondCorp AppConnectors.
///
/// @Snippet(path: "AppConnectorsServiceQuickstart")
public final class AppConnectorsServiceClient: Clients.AppConnectorsServiceProtocol, Sendable {
  let inner: any Clients.AppConnectorsServiceStub
  let pollingErrorPolicy: GoogleGax.PollingErrorPolicy
  let pollingBackoffPolicy: GoogleGax.BackoffPolicy

  /// Creates a new `AppConnectorsServiceClient` instance.
  public init(_ options: GoogleGax.ClientOptions = .init()) throws {
    var inner: any Clients.AppConnectorsServiceStub = try Clients.AppConnectorsServiceTransport(
      options)
    inner = Clients.AppConnectorsServiceRetry(inner, options: options)
    if let logger = options.logger {
      inner = Clients.AppConnectorsServiceLogging(inner, logger: logger)
    }
    self.inner = inner
    self.pollingErrorPolicy = options.pollingErrorPolicy
    self.pollingBackoffPolicy = options.pollingBackoffPolicy
  }

  /// Lists AppConnectors in a given project and location.
  ///
  /// @Snippet(path: "AppConnectorsService_ListAppConnectors")
  public func listAppConnectors(
    request: ListAppConnectorsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudBeyondCorpAppConnectorsV1.ListAppConnectorsResponse {
    try await self.inner.listAppConnectors(request: request, options: options)
  }

  /// Gets details of a single AppConnector.
  ///
  /// @Snippet(path: "AppConnectorsService_GetAppConnector")
  public func getAppConnector(
    request: GetAppConnectorRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudBeyondCorpAppConnectorsV1.AppConnector {
    try await self.inner.getAppConnector(request: request, options: options)
  }

  /// Creates a new AppConnector in a given project and location.
  ///
  /// @Snippet(path: "AppConnectorsService_CreateAppConnector")
  public func createAppConnector(
    request: CreateAppConnectorRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.createAppConnector(request: request, options: options)
  }

  /// Creates a new AppConnector in a given project and location.
  ///
  /// @Snippet(path: "AppConnectorsService_CreateAppConnector")
  public func createAppConnectorPollingUntilDone(
    request: CreateAppConnectorRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<AppConnector> {
    let extractStatus = {
      (op: GoogleLongRunning.Operation) throws
        -> GoogleGax._PollableOperationImpl<AppConnector>.State in
      return try op._extractStatus(AppConnector.self)
    }
    let rawOp = try await self.createAppConnector(request: request, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = { () async throws -> GoogleGax._PollableOperationImpl<AppConnector>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
  }

  /// Updates the parameters of a single AppConnector.
  ///
  /// @Snippet(path: "AppConnectorsService_UpdateAppConnector")
  public func updateAppConnector(
    request: UpdateAppConnectorRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.updateAppConnector(request: request, options: options)
  }

  /// Updates the parameters of a single AppConnector.
  ///
  /// @Snippet(path: "AppConnectorsService_UpdateAppConnector")
  public func updateAppConnectorPollingUntilDone(
    request: UpdateAppConnectorRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<AppConnector> {
    let extractStatus = {
      (op: GoogleLongRunning.Operation) throws
        -> GoogleGax._PollableOperationImpl<AppConnector>.State in
      return try op._extractStatus(AppConnector.self)
    }
    let rawOp = try await self.updateAppConnector(request: request, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = { () async throws -> GoogleGax._PollableOperationImpl<AppConnector>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
  }

  /// Deletes a single AppConnector.
  ///
  /// @Snippet(path: "AppConnectorsService_DeleteAppConnector")
  public func deleteAppConnector(
    request: DeleteAppConnectorRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.deleteAppConnector(request: request, options: options)
  }

  /// Deletes a single AppConnector.
  ///
  /// @Snippet(path: "AppConnectorsService_DeleteAppConnector")
  public func deleteAppConnectorPollingUntilDone(
    request: DeleteAppConnectorRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<Swift.Void> {
    let extractStatus = {
      (op: GoogleLongRunning.Operation) throws -> GoogleGax._PollableOperationImpl<Swift.Void>.State
      in
      return try op._extractStatusEmpty()
    }
    let rawOp = try await self.deleteAppConnector(request: request, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = { () async throws -> GoogleGax._PollableOperationImpl<Swift.Void>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
  }

  /// Report status for a given connector.
  ///
  /// @Snippet(path: "AppConnectorsService_ReportStatus")
  public func reportStatus(
    request: ReportStatusRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.reportStatus(request: request, options: options)
  }

  /// Report status for a given connector.
  ///
  /// @Snippet(path: "AppConnectorsService_ReportStatus")
  public func reportStatusPollingUntilDone(
    request: ReportStatusRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<AppConnector> {
    let extractStatus = {
      (op: GoogleLongRunning.Operation) throws
        -> GoogleGax._PollableOperationImpl<AppConnector>.State in
      return try op._extractStatus(AppConnector.self)
    }
    let rawOp = try await self.reportStatus(request: request, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = { () async throws -> GoogleGax._PollableOperationImpl<AppConnector>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
  }

  /// Lists information about the supported locations for this service.
  ///
  /// @Snippet(path: "AppConnectorsService_ListLocations")
  public func listLocations(
    request: GoogleCloudLocation.ListLocationsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudLocation.ListLocationsResponse {
    try await self.inner.listLocations(request: request, options: options)
  }

  /// Gets information about a location.
  ///
  /// @Snippet(path: "AppConnectorsService_GetLocation")
  public func getLocation(
    request: GoogleCloudLocation.GetLocationRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudLocation.Location {
    try await self.inner.getLocation(request: request, options: options)
  }

  /// Sets the access control policy on the specified resource. Replaces
  /// any existing policy.
  ///
  /// Can return `NOT_FOUND`, `INVALID_ARGUMENT`, and `PERMISSION_DENIED`
  /// errors.
  ///
  /// @Snippet(path: "AppConnectorsService_SetIamPolicy")
  public func setIamPolicy(
    request: GoogleIAMV1.SetIamPolicyRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleIAMV1.Policy {
    try await self.inner.setIamPolicy(request: request, options: options)
  }

  /// Gets the access control policy for a resource. Returns an empty policy
  /// if the resource exists and does not have a policy set.
  ///
  /// @Snippet(path: "AppConnectorsService_GetIamPolicy")
  public func getIamPolicy(
    request: GoogleIAMV1.GetIamPolicyRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleIAMV1.Policy {
    try await self.inner.getIamPolicy(request: request, options: options)
  }

  /// Returns permissions that a caller has on the specified resource. If the
  /// resource does not exist, this will return an empty set of
  /// permissions, not a `NOT_FOUND` error.
  ///
  /// Note: This operation is designed to be used for building
  /// permission-aware UIs and command-line tools, not for authorization
  /// checking. This operation may "fail open" without warning.
  ///
  /// @Snippet(path: "AppConnectorsService_TestIamPermissions")
  public func testIamPermissions(
    request: GoogleIAMV1.TestIamPermissionsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleIAMV1.TestIamPermissionsResponse {
    try await self.inner.testIamPermissions(request: request, options: options)
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+OperationsClient
  ///
  /// @Snippet(path: "AppConnectorsService_ListOperations")
  public func listOperations(
    request: GoogleLongRunning.ListOperationsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.ListOperationsResponse {
    try await self.inner.listOperations(request: request, options: options)
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+OperationsClient
  ///
  /// @Snippet(path: "AppConnectorsService_GetOperation")
  func getOperation(
    request: GoogleLongRunning.GetOperationRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.getOperation(request: request, options: options)
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+OperationsClient
  ///
  /// @Snippet(path: "AppConnectorsService_DeleteOperation")
  public func deleteOperation(
    request: GoogleLongRunning.DeleteOperationRequest, options: GoogleGax.RequestOptions
  ) async throws {
    try await self.inner.deleteOperation(request: request, options: options)
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+OperationsClient
  ///
  /// @Snippet(path: "AppConnectorsService_CancelOperation")
  public func cancelOperation(
    request: GoogleLongRunning.CancelOperationRequest, options: GoogleGax.RequestOptions
  ) async throws {
    try await self.inner.cancelOperation(request: request, options: options)
  }
}

extension Clients {
  /// A Swift protocol to mock `AppConnectorsServiceClient`.
  ///
  /// To mock `AppConnectorsServiceClient` change your functions to receive
  /// `some AppConnectorsServiceProtocol` or `any AppConnectorsServiceProtocol`
  /// and pass a mock implementation in your tests.
  public protocol AppConnectorsServiceProtocol: Sendable {
    /// See `AppConnectorsServiceClient.listAppConnectors`.
    func listAppConnectors(
      request: ListAppConnectorsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudBeyondCorpAppConnectorsV1.ListAppConnectorsResponse

    /// See `AppConnectorsServiceClient.getAppConnector`.
    func getAppConnector(
      request: GetAppConnectorRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudBeyondCorpAppConnectorsV1.AppConnector

    /// See `AppConnectorsServiceClient.createAppConnector`.
    func createAppConnector(
      request: CreateAppConnectorRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `AppConnectorsServiceClient.createAppConnector`.
    func createAppConnectorPollingUntilDone(
      request: CreateAppConnectorRequest, options: GoogleGax.RequestOptions
    ) async throws -> any GoogleGax.PollableOperation<AppConnector>

    /// See `AppConnectorsServiceClient.updateAppConnector`.
    func updateAppConnector(
      request: UpdateAppConnectorRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `AppConnectorsServiceClient.updateAppConnector`.
    func updateAppConnectorPollingUntilDone(
      request: UpdateAppConnectorRequest, options: GoogleGax.RequestOptions
    ) async throws -> any GoogleGax.PollableOperation<AppConnector>

    /// See `AppConnectorsServiceClient.deleteAppConnector`.
    func deleteAppConnector(
      request: DeleteAppConnectorRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `AppConnectorsServiceClient.deleteAppConnector`.
    func deleteAppConnectorPollingUntilDone(
      request: DeleteAppConnectorRequest, options: GoogleGax.RequestOptions
    ) async throws -> any GoogleGax.PollableOperation<Swift.Void>

    /// See `AppConnectorsServiceClient.reportStatus`.
    func reportStatus(
      request: ReportStatusRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `AppConnectorsServiceClient.reportStatus`.
    func reportStatusPollingUntilDone(
      request: ReportStatusRequest, options: GoogleGax.RequestOptions
    ) async throws -> any GoogleGax.PollableOperation<AppConnector>

    /// See `AppConnectorsServiceClient.listLocations`.
    func listLocations(
      request: GoogleCloudLocation.ListLocationsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudLocation.ListLocationsResponse

    /// See `AppConnectorsServiceClient.getLocation`.
    func getLocation(
      request: GoogleCloudLocation.GetLocationRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudLocation.Location

    /// See `AppConnectorsServiceClient.setIamPolicy`.
    func setIamPolicy(
      request: GoogleIAMV1.SetIamPolicyRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleIAMV1.Policy

    /// See `AppConnectorsServiceClient.getIamPolicy`.
    func getIamPolicy(
      request: GoogleIAMV1.GetIamPolicyRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleIAMV1.Policy

    /// See `AppConnectorsServiceClient.testIamPermissions`.
    func testIamPermissions(
      request: GoogleIAMV1.TestIamPermissionsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleIAMV1.TestIamPermissionsResponse

    /// See `AppConnectorsServiceClient.listOperations`.
    func listOperations(
      request: GoogleLongRunning.ListOperationsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.ListOperationsResponse

    /// See `AppConnectorsServiceClient.deleteOperation`.
    func deleteOperation(
      request: GoogleLongRunning.DeleteOperationRequest, options: GoogleGax.RequestOptions
    ) async throws

    /// See `AppConnectorsServiceClient.cancelOperation`.
    func cancelOperation(
      request: GoogleLongRunning.CancelOperationRequest, options: GoogleGax.RequestOptions
    ) async throws
  }
}

// Default implementations
extension Clients.AppConnectorsServiceProtocol {
  public func listAppConnectors(request: ListAppConnectorsRequest) async throws
    -> GoogleCloudBeyondCorpAppConnectorsV1.ListAppConnectorsResponse
  {
    try await self.listAppConnectors(request: request, options: .init())
  }

  public func listAppConnectors(
    request: ListAppConnectorsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudBeyondCorpAppConnectorsV1.ListAppConnectorsResponse {
    throw GoogleGax.RequestError.unimplemented
  }

  public func listAppConnectorsByItems(
    request: ListAppConnectorsRequest
  ) -> any AsyncSequence<AppConnector, Swift.Error> & Sendable {
    self.listAppConnectorsByItems(request: request, options: .init())
  }

  /// Lists AppConnectors in a given project and location.
  ///
  /// @Snippet(path: "AppConnectorsService_ListAppConnectors")
  public func listAppConnectorsByItems(
    request: ListAppConnectorsRequest, options: GoogleGax.RequestOptions
  ) -> any AsyncSequence<AppConnector, Swift.Error> & Sendable {
    let listRpc = {
      @Sendable (token: Swift.String) async throws
        -> GoogleCloudBeyondCorpAppConnectorsV1.ListAppConnectorsResponse in
      var request = request
      request.pageToken = token
      return try await self.listAppConnectors(request: request, options: options)
    }
    return GoogleGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func listAppConnectorsByItems(
    parent: Swift.String,
  ) -> any AsyncSequence<AppConnector, Swift.Error> & Sendable {
    let request = ListAppConnectorsRequest().with {
      $0.parent = parent
    }
    return self.listAppConnectorsByItems(request: request)
  }

  public func getAppConnector(request: GetAppConnectorRequest) async throws
    -> GoogleCloudBeyondCorpAppConnectorsV1.AppConnector
  {
    try await self.getAppConnector(request: request, options: .init())
  }

  public func getAppConnector(
    request: GetAppConnectorRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudBeyondCorpAppConnectorsV1.AppConnector {
    throw GoogleGax.RequestError.unimplemented
  }

  public func getAppConnector(
    name: Swift.String,
  ) async throws -> GoogleCloudBeyondCorpAppConnectorsV1.AppConnector {
    let request = GetAppConnectorRequest().with {
      $0.name = name
    }
    return try await self.getAppConnector(request: request)
  }

  public func createAppConnector(request: CreateAppConnectorRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.createAppConnector(request: request, options: .init())
  }

  public func createAppConnector(
    request: CreateAppConnectorRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleGax.RequestError.unimplemented
  }

  public func createAppConnectorPollingUntilDone(request: CreateAppConnectorRequest) async throws
    -> any GoogleGax.PollableOperation<AppConnector>
  {
    try await self.createAppConnectorPollingUntilDone(request: request, options: .init())
  }

  public func createAppConnectorPollingUntilDone(
    request: CreateAppConnectorRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<AppConnector> {
    let poll = { () async throws -> GoogleGax._PollableOperationImpl<AppConnector>.State in
      throw GoogleGax.RequestError.unimplemented
    }
    return GoogleGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func createAppConnectorPollingUntilDone(
    parent: Swift.String,
    appConnector: AppConnector?,
    appConnectorId: Swift.String,
  ) async throws -> any GoogleGax.PollableOperation<AppConnector> {
    let request = CreateAppConnectorRequest().with {
      $0.parent = parent
      $0.appConnector = appConnector
      $0.appConnectorId = appConnectorId
    }
    return try await self.createAppConnectorPollingUntilDone(request: request)
  }

  public func updateAppConnector(request: UpdateAppConnectorRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.updateAppConnector(request: request, options: .init())
  }

  public func updateAppConnector(
    request: UpdateAppConnectorRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleGax.RequestError.unimplemented
  }

  public func updateAppConnectorPollingUntilDone(request: UpdateAppConnectorRequest) async throws
    -> any GoogleGax.PollableOperation<AppConnector>
  {
    try await self.updateAppConnectorPollingUntilDone(request: request, options: .init())
  }

  public func updateAppConnectorPollingUntilDone(
    request: UpdateAppConnectorRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<AppConnector> {
    let poll = { () async throws -> GoogleGax._PollableOperationImpl<AppConnector>.State in
      throw GoogleGax.RequestError.unimplemented
    }
    return GoogleGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func updateAppConnectorPollingUntilDone(
    appConnector: AppConnector?,
    updateMask: GoogleWKT.WKTFieldMask?,
  ) async throws -> any GoogleGax.PollableOperation<AppConnector> {
    let request = UpdateAppConnectorRequest().with {
      $0.appConnector = appConnector
      $0.updateMask = updateMask
    }
    return try await self.updateAppConnectorPollingUntilDone(request: request)
  }

  public func deleteAppConnector(request: DeleteAppConnectorRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.deleteAppConnector(request: request, options: .init())
  }

  public func deleteAppConnector(
    request: DeleteAppConnectorRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleGax.RequestError.unimplemented
  }

  public func deleteAppConnectorPollingUntilDone(request: DeleteAppConnectorRequest) async throws
    -> any GoogleGax.PollableOperation<Swift.Void>
  {
    try await self.deleteAppConnectorPollingUntilDone(request: request, options: .init())
  }

  public func deleteAppConnectorPollingUntilDone(
    request: DeleteAppConnectorRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<Swift.Void> {
    let poll = { () async throws -> GoogleGax._PollableOperationImpl<Swift.Void>.State in
      throw GoogleGax.RequestError.unimplemented
    }
    return GoogleGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func deleteAppConnectorPollingUntilDone(
    name: Swift.String,
  ) async throws -> any GoogleGax.PollableOperation<Swift.Void> {
    let request = DeleteAppConnectorRequest().with {
      $0.name = name
    }
    return try await self.deleteAppConnectorPollingUntilDone(request: request)
  }

  public func reportStatus(request: ReportStatusRequest) async throws -> GoogleLongRunning.Operation
  {
    try await self.reportStatus(request: request, options: .init())
  }

  public func reportStatus(
    request: ReportStatusRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleGax.RequestError.unimplemented
  }

  public func reportStatusPollingUntilDone(request: ReportStatusRequest) async throws
    -> any GoogleGax.PollableOperation<AppConnector>
  {
    try await self.reportStatusPollingUntilDone(request: request, options: .init())
  }

  public func reportStatusPollingUntilDone(
    request: ReportStatusRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<AppConnector> {
    let poll = { () async throws -> GoogleGax._PollableOperationImpl<AppConnector>.State in
      throw GoogleGax.RequestError.unimplemented
    }
    return GoogleGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func reportStatusPollingUntilDone(
    appConnector: Swift.String,
    resourceInfo: ResourceInfo?,
  ) async throws -> any GoogleGax.PollableOperation<AppConnector> {
    let request = ReportStatusRequest().with {
      $0.appConnector = appConnector
      $0.resourceInfo = resourceInfo
    }
    return try await self.reportStatusPollingUntilDone(request: request)
  }

  public func listLocations(request: GoogleCloudLocation.ListLocationsRequest) async throws
    -> GoogleCloudLocation.ListLocationsResponse
  {
    try await self.listLocations(request: request, options: .init())
  }

  public func listLocations(
    request: GoogleCloudLocation.ListLocationsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudLocation.ListLocationsResponse {
    throw GoogleGax.RequestError.unimplemented
  }

  public func listLocationsByItems(
    request: GoogleCloudLocation.ListLocationsRequest
  ) -> any AsyncSequence<GoogleCloudLocation.Location, Swift.Error> & Sendable {
    self.listLocationsByItems(request: request, options: .init())
  }

  /// Lists information about the supported locations for this service.
  ///
  /// @Snippet(path: "AppConnectorsService_ListLocations")
  public func listLocationsByItems(
    request: GoogleCloudLocation.ListLocationsRequest, options: GoogleGax.RequestOptions
  ) -> any AsyncSequence<GoogleCloudLocation.Location, Swift.Error> & Sendable {
    let listRpc = {
      @Sendable (token: Swift.String) async throws -> GoogleCloudLocation.ListLocationsResponse in
      var request = request
      request.pageToken = token
      return try await self.listLocations(request: request, options: options)
    }
    return GoogleGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func getLocation(request: GoogleCloudLocation.GetLocationRequest) async throws
    -> GoogleCloudLocation.Location
  {
    try await self.getLocation(request: request, options: .init())
  }

  public func getLocation(
    request: GoogleCloudLocation.GetLocationRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudLocation.Location {
    throw GoogleGax.RequestError.unimplemented
  }

  public func setIamPolicy(request: GoogleIAMV1.SetIamPolicyRequest) async throws
    -> GoogleIAMV1.Policy
  {
    try await self.setIamPolicy(request: request, options: .init())
  }

  public func setIamPolicy(
    request: GoogleIAMV1.SetIamPolicyRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleIAMV1.Policy {
    throw GoogleGax.RequestError.unimplemented
  }

  public func getIamPolicy(request: GoogleIAMV1.GetIamPolicyRequest) async throws
    -> GoogleIAMV1.Policy
  {
    try await self.getIamPolicy(request: request, options: .init())
  }

  public func getIamPolicy(
    request: GoogleIAMV1.GetIamPolicyRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleIAMV1.Policy {
    throw GoogleGax.RequestError.unimplemented
  }

  public func testIamPermissions(request: GoogleIAMV1.TestIamPermissionsRequest) async throws
    -> GoogleIAMV1.TestIamPermissionsResponse
  {
    try await self.testIamPermissions(request: request, options: .init())
  }

  public func testIamPermissions(
    request: GoogleIAMV1.TestIamPermissionsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleIAMV1.TestIamPermissionsResponse {
    throw GoogleGax.RequestError.unimplemented
  }

  public func listOperations(request: GoogleLongRunning.ListOperationsRequest) async throws
    -> GoogleLongRunning.ListOperationsResponse
  {
    try await self.listOperations(request: request, options: .init())
  }

  public func listOperations(
    request: GoogleLongRunning.ListOperationsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.ListOperationsResponse {
    throw GoogleGax.RequestError.unimplemented
  }

  public func listOperationsByItems(
    request: GoogleLongRunning.ListOperationsRequest
  ) -> any AsyncSequence<GoogleLongRunning.Operation, Swift.Error> & Sendable {
    self.listOperationsByItems(request: request, options: .init())
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+OperationsClient
  ///
  /// @Snippet(path: "AppConnectorsService_ListOperations")
  public func listOperationsByItems(
    request: GoogleLongRunning.ListOperationsRequest, options: GoogleGax.RequestOptions
  ) -> any AsyncSequence<GoogleLongRunning.Operation, Swift.Error> & Sendable {
    let listRpc = {
      @Sendable (token: Swift.String) async throws -> GoogleLongRunning.ListOperationsResponse in
      var request = request
      request.pageToken = token
      return try await self.listOperations(request: request, options: options)
    }
    return GoogleGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func listOperationsByItems(
    name: Swift.String,
    filter: Swift.String,
  ) -> any AsyncSequence<GoogleLongRunning.Operation, Swift.Error> & Sendable {
    let request = GoogleLongRunning.ListOperationsRequest().with {
      $0.name = name
      $0.filter = filter
    }
    return self.listOperationsByItems(request: request)
  }

  public func getOperation(request: GoogleLongRunning.GetOperationRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.getOperation(request: request, options: .init())
  }

  public func getOperation(
    request: GoogleLongRunning.GetOperationRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleGax.RequestError.unimplemented
  }

  public func getOperation(
    name: Swift.String,
  ) async throws -> GoogleLongRunning.Operation {
    let request = GoogleLongRunning.GetOperationRequest().with {
      $0.name = name
    }
    return try await self.getOperation(request: request)
  }

  public func deleteOperation(request: GoogleLongRunning.DeleteOperationRequest) async throws {
    try await self.deleteOperation(request: request, options: .init())
  }

  public func deleteOperation(
    request: GoogleLongRunning.DeleteOperationRequest, options: GoogleGax.RequestOptions
  ) async throws {
    throw GoogleGax.RequestError.unimplemented
  }

  public func deleteOperation(
    name: Swift.String,
  ) async throws {
    let request = GoogleLongRunning.DeleteOperationRequest().with {
      $0.name = name
    }
    try await self.deleteOperation(request: request)
  }

  public func cancelOperation(request: GoogleLongRunning.CancelOperationRequest) async throws {
    try await self.cancelOperation(request: request, options: .init())
  }

  public func cancelOperation(
    request: GoogleLongRunning.CancelOperationRequest, options: GoogleGax.RequestOptions
  ) async throws {
    throw GoogleGax.RequestError.unimplemented
  }

  public func cancelOperation(
    name: Swift.String,
  ) async throws {
    let request = GoogleLongRunning.CancelOperationRequest().with {
      $0.name = name
    }
    try await self.cancelOperation(request: request)
  }
}
