// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// ContainerHealthDetails reflects the health details of a container.
public struct ContainerHealthDetails: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// The version of the expected config.
  public var expectedConfigVersion: Swift.String = Swift.String()

  /// The version of the current config.
  public var currentConfigVersion: Swift.String = Swift.String()

  /// The extended status. Such as ExitCode, StartedAt, FinishedAt, etc.
  public var extendedStatus: [Swift.String: Swift.String] = [:]

  /// The latest error message.
  public var errorMsg: Swift.String = Swift.String()

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `ContainerHealthDetails`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ContainerHealthDetails().with { $0.expectedConfigVersion = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let expectedConfigVersion = CodingKeys(stringValue: "expectedConfigVersion")
    static let currentConfigVersion = CodingKeys(stringValue: "currentConfigVersion")
    static let extendedStatus = CodingKeys(stringValue: "extendedStatus")
    static let errorMsg = CodingKeys(stringValue: "errorMsg")

    static let _knownKeys: Set<Swift.String> = [
      "expectedConfigVersion",
      "currentConfigVersion",
      "extendedStatus",
      "errorMsg",
    ]
  }

  public init(from decoder: any Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .expectedConfigVersion)
    {
      self.expectedConfigVersion = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .currentConfigVersion) {
      self.currentConfigVersion = value
    }
    if let value = try container.decodeIfPresent(
      [Swift.String: Swift.String].self, forKey: .extendedStatus)
    {
      self.extendedStatus = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .errorMsg) {
      self.errorMsg = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: any Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.expectedConfigVersion, forKey: .expectedConfigVersion)
    try container.encode(self.currentConfigVersion, forKey: .currentConfigVersion)
    try container.encode(self.extendedStatus, forKey: .extendedStatus)
    try container.encode(self.errorMsg, forKey: .errorMsg)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// The type URL for `ContainerHealthDetails`: `"type.googleapis.com/google.cloud.beyondcorp.appconnectors.v1.ContainerHealthDetails"`.
  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.beyondcorp.appconnectors.v1.ContainerHealthDetails"
  }

  /// Initialize an instance of `ContainerHealthDetails` by unpacking from a `GoogleWKT.WKTAny`.
  ///
  /// - Parameter any: The `GoogleWKT.WKTAny` instance to unpack.
  /// - Throws: An error if the type URL in `any` does not match `"type.googleapis.com/google.cloud.beyondcorp.appconnectors.v1.ContainerHealthDetails"`,
  ///   or if deserialization fails.
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }

  /// Packs this `ContainerHealthDetails` into a `GoogleWKT.WKTStruct` representation.
  ///
  /// - Throws: An error if serialization fails.
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
