// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// ResourceInfo represents the information/status of an app connector resource.
/// Such as:
/// - remote_agent
///   - container
///     - runtime
///     - appgateway
///       - appconnector
///         - appconnection
///           - tunnel
///       - logagent
public struct ResourceInfo: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// Required. Unique Id for the resource.
  public var id: Swift.String = Swift.String()

  /// Overall health status. Overall status is derived based on the status of
  /// each sub level resources.
  public var status: HealthStatus = HealthStatus()

  /// Specific details for the resource. This is for internal use only.
  public var resource: GoogleCloudWKT.`Any`? = nil

  /// The timestamp to collect the info. It is suggested to be set by
  /// the topmost level resource only.
  public var time: GoogleCloudWKT.Timestamp? = nil

  /// List of Info for the sub level resources.
  public var sub: [ResourceInfo] = []

  /// Initialize a new instance of `ResourceInfo`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ResourceInfo().with { $0.id = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.beyondcorp.appconnectors.v1.ResourceInfo"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
